site_name: NSTEP-Stoytelling Docs
site_url: https://ualberta-cmput401.github.io/nstep-storytelling/
nav:
    - Project Requirements: index.md
    - Software Design: design.md
    - Project Management: project management.md
    - Teamwork: teamwork.md
repo_url: https://github.com/UAlberta-CMPUT401/nstep-storytelling
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - glightbox