site_name: NSTEP-Storytelling Docs
site_url: https://ualberta-cmput401.github.io/nstep-storytelling/
nav:
    - Project Requirements: index.md
    - Software Design: design.md
    - Project Management: project management.md
    - Teamwork: teamwork.md
repo_url: https://github.com/UAlberta-CMPUT401/nstep-storytelling
site_description: NSTEP is different than other health promotion programs in its success at being accepted, integrated and supported by school staff and administration at all levels of the education system as well as community agencies. Our program is sought after by teachers because it provides curriculum and activities that teaches children and youth how to build communities inside the places they spend the greater part of their lives.
edit_uri: edit/main/docs/

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - glightbox