# Generated by Django 4.0.6 on 2022-10-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
