# Generated by Django 4.1.1 on 2022-11-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profileImage',
        ),
    ]
