# Generated by Django 4.0.6 on 2022-10-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
