# Generated by Django 4.0.6 on 2022-10-15 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('url', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('content_type', models.CharField(choices=[('TEXT', 'Text'), ('VOICE', 'Voice'), ('VIDEO', 'Video')], default='TEXT', max_length=20)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('url', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('answers', models.ManyToManyField(to='questionnaire.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('questions', models.ManyToManyField(to='questionnaire.question')),
            ],
        ),
    ]
