# Generated by Django 4.1.1 on 2022-11-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_rename_answers_answerlist_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
