# Generated by Django 4.1.1 on 2022-11-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_rename_answers_answerlist_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content_audio',
            field=models.FileField(null=True, upload_to='uploads/audioFiles/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='content_video',
            field=models.FileField(null=True, upload_to='uploads/videoFiles/'),
        ),
    ]
