# Generated by Django 4.1.1 on 2022-11-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_alter_answer_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
