# Generated by Django 4.1.1 on 2022-11-16 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_answer_content_audio_answer_content_video'),
        ('questionnaire', '0004_alter_answer_content'),
    ]

    operations = [
    ]
