# Generated by Django 4.1.1 on 2022-11-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_question_allow_recording_alter_answer_content_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content_audio',
            field=models.TextField(blank=True, max_length=999999999999, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content_video',
            field=models.TextField(blank=True, max_length=999999999999, null=True),
        ),
    ]
