# Generated by Django 4.1.1 on 2022-11-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_merge_20221119_1152'),
        ('questionnaire', '0007_alter_answer_content_audio_and_more'),
    ]

    operations = [
    ]
