# Generated by Django 4.1.1 on 2022-11-26 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_historicalquestionnaire_historicalquestion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerlist',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['time']},
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
