# Generated by Django 4.1.1 on 2022-11-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_options_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='content',
        ),
        migrations.AlterField(
            model_name='event',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('modify', 'Modify'), ('delete', 'Delete'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(choices=[('feedbacks', 'Feedback'), ('questionnaire', 'Questionnaire'), ('user', 'User'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
